Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2020-08, with the labels that each got.

#165 chore: bump opentelemetry core dependencies
  examples/dns/package.json
  examples/express/package.json
  examples/grpc-census-prop/package.json
  examples/grpc_dynamic_codegen/package.json
  examples/ioredis/package.json
  examples/mongodb/package.json
  examples/mysql/package.json
  examples/postgres/package.json
  examples/redis/package.json
  packages/opentelemetry-test-utils/package.json
  plugins/node/opentelemetry-plugin-dns/package.json
  plugins/node/opentelemetry-plugin-express/package.json
  plugins/node/opentelemetry-plugin-ioredis/package.json
  plugins/node/opentelemetry-plugin-mongodb/package.json
  plugins/node/opentelemetry-plugin-mysql/package.json
  plugins/node/opentelemetry-plugin-pg-pool/package.json
  plugins/node/opentelemetry-plugin-pg/package.json
  plugins/node/opentelemetry-plugin-redis/package.json
  plugins/web/opentelemetry-plugin-document-load/package.json
  plugins/web/opentelemetry-plugin-user-interaction/package.json
  plugins/web/opentelemetry-plugin-user-interaction/test/userInteraction.nozone.test.ts
  plugins/web/opentelemetry-plugin-user-interaction/test/userInteraction.test.ts
  propagators/opentelemetry-propagator-grpc-census-binary/package.json
  propagators/opentelemetry-propagator-jaeger/package.json
Labels: enhancement

#170 fix: various compilation errors
  plugins/node/opentelemetry-plugin-dns/package.json
  plugins/node/opentelemetry-plugin-express/package.json
  plugins/node/opentelemetry-plugin-ioredis/package.json
  plugins/node/opentelemetry-plugin-mongodb/package.json
  plugins/node/opentelemetry-plugin-mysql/package.json
  plugins/node/opentelemetry-plugin-mysql/src/types.ts
  plugins/node/opentelemetry-plugin-mysql/src/utils.ts
  plugins/node/opentelemetry-plugin-pg-pool/package.json
  plugins/node/opentelemetry-plugin-pg/package.json
  plugins/node/opentelemetry-plugin-redis/package.json
  plugins/web/opentelemetry-plugin-user-interaction/package.json
  propagators/opentelemetry-propagator-grpc-census-binary/package.json
Labels: dependencies

#172 [Plugin User Interaction]: Improve causality of spans from bubbled events
  plugins/web/opentelemetry-plugin-user-interaction/src/userInteraction.ts
  plugins/web/opentelemetry-plugin-user-interaction/test/userInteraction.nozone.test.ts
Labels: enhancement

#144 feat: adding Koa instrumentation
  examples/koa/README.md
  examples/koa/client.js
  examples/koa/images/jaeger.jpg
  examples/koa/images/zipkin.jpg
  examples/koa/package.json
  examples/koa/server.js
  examples/koa/tracer.js
  plugins/node/opentelemetry-koa-instrumentation/.eslintignore
  plugins/node/opentelemetry-koa-instrumentation/.eslintrc.js
  plugins/node/opentelemetry-koa-instrumentation/.npmignore
  plugins/node/opentelemetry-koa-instrumentation/LICENSE
  plugins/node/opentelemetry-koa-instrumentation/README.md
  plugins/node/opentelemetry-koa-instrumentation/package.json
  plugins/node/opentelemetry-koa-instrumentation/src/index.ts
  plugins/node/opentelemetry-koa-instrumentation/src/koa.ts
  plugins/node/opentelemetry-koa-instrumentation/src/types.ts
  plugins/node/opentelemetry-koa-instrumentation/src/utils.ts
  plugins/node/opentelemetry-koa-instrumentation/src/version.ts
  plugins/node/opentelemetry-koa-instrumentation/test/koa-router.test.ts
  plugins/node/opentelemetry-koa-instrumentation/test/koa.test.ts
  plugins/node/opentelemetry-koa-instrumentation/tsconfig.json
Labels: Internship Ending Soon

#171 feat: Hapi auto-instrumentation
  examples/hapi/README.md
  examples/hapi/client.js
  examples/hapi/images/jaeger.jpg
  examples/hapi/images/zipkin.jpg
  examples/hapi/package.json
  examples/hapi/server.js
  examples/hapi/tracer.js
  plugins/node/opentelemetry-hapi-instrumentation/.eslintignore
  plugins/node/opentelemetry-hapi-instrumentation/.eslintrc.js
  plugins/node/opentelemetry-hapi-instrumentation/.mocharc.js
  plugins/node/opentelemetry-hapi-instrumentation/.npmignore
  plugins/node/opentelemetry-hapi-instrumentation/LICENSE
  plugins/node/opentelemetry-hapi-instrumentation/README.md
  plugins/node/opentelemetry-hapi-instrumentation/package.json
  plugins/node/opentelemetry-hapi-instrumentation/src/hapi.ts
  plugins/node/opentelemetry-hapi-instrumentation/src/index.ts
  plugins/node/opentelemetry-hapi-instrumentation/src/types.ts
  plugins/node/opentelemetry-hapi-instrumentation/src/utils.ts
  plugins/node/opentelemetry-hapi-instrumentation/src/version.ts
  plugins/node/opentelemetry-hapi-instrumentation/test/hapi-plugin.test.ts
  plugins/node/opentelemetry-hapi-instrumentation/test/hapi-server-ext.test.ts
  plugins/node/opentelemetry-hapi-instrumentation/test/hapi.test.ts
  plugins/node/opentelemetry-hapi-instrumentation/test/testPackage.json
  plugins/node/opentelemetry-hapi-instrumentation/tsconfig.json
Labels: Internship Ending Soon
