Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2020-06, with the labels that each got.

#39 feat: add gRPC Census propagator
  propagators/opentelemetry-propagator-grpc-census-binary/LICENSE
  propagators/opentelemetry-propagator-grpc-census-binary/README.md
  propagators/opentelemetry-propagator-grpc-census-binary/package.json
  propagators/opentelemetry-propagator-grpc-census-binary/src/BinaryTraceContext.ts
  propagators/opentelemetry-propagator-grpc-census-binary/src/GrpcCensusPropagator.ts
  propagators/opentelemetry-propagator-grpc-census-binary/src/index.ts
  propagators/opentelemetry-propagator-grpc-census-binary/src/version.ts
  propagators/opentelemetry-propagator-grpc-census-binary/test/BinaryTraceContext.test.ts
  propagators/opentelemetry-propagator-grpc-census-binary/test/GrpcCensusPropagator.test.ts
  propagators/opentelemetry-propagator-grpc-census-binary/tsconfig.json
  propagators/opentelemetry-propagator-grpc-census-binary/tslint.json
Labels: enhancement

#43 improv(express): require parent span #8
  plugins/node/opentelemetry-plugin-express/src/express.ts
  plugins/node/opentelemetry-plugin-express/test/express.test.ts
Labels: size/L

#42 improv(ioredis): require parent span
  plugins/node/opentelemetry-plugin-ioredis/package.json
  plugins/node/opentelemetry-plugin-ioredis/src/utils.ts
  plugins/node/opentelemetry-plugin-ioredis/test/ioredis.test.ts
Labels: size/M

#88 chore: fixing running task in a proper zone preserving the active zone
  plugins/web/opentelemetry-plugin-user-interaction/package.json
  plugins/web/opentelemetry-plugin-user-interaction/src/userInteraction.ts
  plugins/web/opentelemetry-plugin-user-interaction/test/userInteraction.test.ts
Labels: size/M

#106 fix(express): avoid unref since not available in node 8 #78
  plugins/node/opentelemetry-plugin-express/src/express.ts
Labels: size/XS
