Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2020-12, with the labels that each got.

#268 fix: missing .fields() method in jaeger propagator
  propagators/opentelemetry-propagator-jaeger/src/JaegerHttpTracePropagator.ts
  propagators/opentelemetry-propagator-jaeger/test/JaegerHttpTracePropagator.test.ts
Labels: enhancement

#265 feat: Add GitHub Actions Resource Detector
  detectors/node/opentelemetry-resource-detector-github/.eslintignore
  detectors/node/opentelemetry-resource-detector-github/.eslintrc.js
  detectors/node/opentelemetry-resource-detector-github/.npmignore
  detectors/node/opentelemetry-resource-detector-github/LICENSE
  detectors/node/opentelemetry-resource-detector-github/README.md
  detectors/node/opentelemetry-resource-detector-github/package.json
  detectors/node/opentelemetry-resource-detector-github/src/detectors/GitHubDetector.ts
  detectors/node/opentelemetry-resource-detector-github/src/detectors/index.ts
  detectors/node/opentelemetry-resource-detector-github/src/index.ts
  detectors/node/opentelemetry-resource-detector-github/src/version.ts
  detectors/node/opentelemetry-resource-detector-github/test/detectors/GitHubDetector.test.ts
  detectors/node/opentelemetry-resource-detector-github/tsconfig.json
  lerna.json
Labels: enhancement

#241 fix(ioredis): set `net.peer.name` attribute according to spec
  plugins/node/opentelemetry-plugin-ioredis/src/utils.ts
  plugins/node/opentelemetry-plugin-ioredis/test/ioredis.test.ts
Labels: bug

#283 chore: update to OTel v0.14.0
  detectors/node/opentelemetry-resource-detector-github/package.json
  examples/dns/package.json
  examples/express/package.json
  examples/graphql/package.json
  examples/grpc-census-prop/package.json
  examples/hapi/package.json
  examples/host-metrics/package.json
  examples/ioredis/package.json
  examples/koa/package.json
  examples/mysql/package.json
  examples/postgres/package.json
  examples/react-load/preact/package.json
  examples/react-load/react/package.json
  examples/redis/package.json
  metapackages/plugins-node-core-and-contrib/package.json
  packages/opentelemetry-host-metrics/package.json
  packages/opentelemetry-host-metrics/src/metric.ts
  packages/opentelemetry-host-metrics/test/metric.test.ts
  packages/opentelemetry-test-utils/package.json
  plugins/node/opentelemetry-hapi-instrumentation/package.json
  plugins/node/opentelemetry-instrumentation-graphql/package.json
  plugins/node/opentelemetry-koa-instrumentation/package.json
  plugins/node/opentelemetry-plugin-dns/package.json
  plugins/node/opentelemetry-plugin-dns/src/types.ts
  plugins/node/opentelemetry-plugin-express/package.json
  plugins/node/opentelemetry-plugin-express/src/types.ts
  plugins/node/opentelemetry-plugin-ioredis/package.json
  plugins/node/opentelemetry-plugin-ioredis/src/types.ts
  plugins/node/opentelemetry-plugin-mongodb/package.json
  plugins/node/opentelemetry-plugin-mongodb/test/mongodb.test.ts
  plugins/node/opentelemetry-plugin-mysql/package.json
  plugins/node/opentelemetry-plugin-pg-pool/package.json
  plugins/node/opentelemetry-plugin-pg/package.json
  plugins/node/opentelemetry-plugin-pg/src/utils.ts
  plugins/node/opentelemetry-plugin-pg/test/utils.test.ts
  plugins/node/opentelemetry-plugin-redis/package.json
  plugins/web/opentelemetry-plugin-document-load/package.json
  plugins/web/opentelemetry-plugin-document-load/src/documentLoad.ts
  plugins/web/opentelemetry-plugin-document-load/test/documentLoad.test.ts
  plugins/web/opentelemetry-plugin-react-load/package.json
  plugins/web/opentelemetry-plugin-user-interaction/package.json
  propagators/opentelemetry-propagator-grpc-census-binary/package.json
  propagators/opentelemetry-propagator-jaeger/package.json
Labels: internal

#290 docs: fix links to examples
  plugins/node/opentelemetry-plugin-express/README.md
  plugins/node/opentelemetry-plugin-mongodb/README.md
  plugins/node/opentelemetry-plugin-mysql/README.md
  plugins/node/opentelemetry-plugin-pg-pool/README.md
  plugins/node/opentelemetry-plugin-pg/README.md
  plugins/node/opentelemetry-plugin-redis/README.md
Labels: bug
