Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2021-04, with the labels that each got.

#408 chore: bump otel dependencies to latest patch
  metapackages/plugins-node-core-and-contrib/package.json
  packages/opentelemetry-host-metrics/package.json
  packages/opentelemetry-test-utils/package.json
  plugins/node/opentelemetry-instrumentation-dns/package.json
  plugins/node/opentelemetry-instrumentation-express/package.json
  plugins/node/opentelemetry-instrumentation-graphql/package.json
  plugins/node/opentelemetry-instrumentation-hapi/package.json
  plugins/node/opentelemetry-instrumentation-ioredis/package.json
  plugins/node/opentelemetry-instrumentation-koa/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/package.json
  plugins/node/opentelemetry-instrumentation-mysql/package.json
  plugins/node/opentelemetry-instrumentation-net/package.json
  plugins/node/opentelemetry-instrumentation-pg/package.json
  plugins/node/opentelemetry-instrumentation-redis/package.json
  plugins/node/opentelemetry-plugin-dns/package.json
  plugins/node/opentelemetry-plugin-express/package.json
  plugins/node/opentelemetry-plugin-ioredis/package.json
  plugins/node/opentelemetry-plugin-mongodb/package.json
  plugins/node/opentelemetry-plugin-mysql/package.json
  plugins/node/opentelemetry-plugin-pg-pool/package.json
  plugins/node/opentelemetry-plugin-pg/package.json
  plugins/node/opentelemetry-plugin-redis/package.json
  plugins/web/opentelemetry-instrumentation-user-interaction/package.json
  plugins/web/opentelemetry-plugin-react-load/package.json
Labels: internal

#413 document: fix express example
  examples/express/client.js
  examples/express/package.json
  examples/express/server.js
  examples/express/tracer.js
  plugins/node/opentelemetry-instrumentation-express/README.md
Labels: documentation

#403 chore: fixing context propagation on mongo callback
  examples/mongodb/package.json
  examples/mongodb/server.js
  examples/mongodb/tracer.js
  plugins/node/opentelemetry-instrumentation-mongodb/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/src/mongodb.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb.test.ts
Labels: bug

#419 feat: bunyan instrumentation
  plugins/node/opentelemetry-instrumentation-bunyan/.eslintignore
  plugins/node/opentelemetry-instrumentation-bunyan/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-bunyan/.npmignore
  plugins/node/opentelemetry-instrumentation-bunyan/LICENSE
  plugins/node/opentelemetry-instrumentation-bunyan/README.md
  plugins/node/opentelemetry-instrumentation-bunyan/package.json
  plugins/node/opentelemetry-instrumentation-bunyan/src/bunyan.ts
  plugins/node/opentelemetry-instrumentation-bunyan/src/index.ts
  plugins/node/opentelemetry-instrumentation-bunyan/src/types.ts
  plugins/node/opentelemetry-instrumentation-bunyan/src/version.ts
  plugins/node/opentelemetry-instrumentation-bunyan/test/bunyan.test.ts
  plugins/node/opentelemetry-instrumentation-bunyan/tsconfig.json
Labels: enhancement

#416 feat: restify instrumentation
  examples/restify/README.md
  examples/restify/client.js
  examples/restify/images/jaeger-ui.png
  examples/restify/images/zipkin-ui.png
  examples/restify/package.json
  examples/restify/server.js
  examples/restify/tracer.js
  plugins/node/opentelemetry-instrumentation-restify/.eslintignore
  plugins/node/opentelemetry-instrumentation-restify/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-restify/.npmignore
  plugins/node/opentelemetry-instrumentation-restify/LICENSE
  plugins/node/opentelemetry-instrumentation-restify/README.md
  plugins/node/opentelemetry-instrumentation-restify/package.json
  plugins/node/opentelemetry-instrumentation-restify/src/constants.ts
  plugins/node/opentelemetry-instrumentation-restify/src/index.ts
  plugins/node/opentelemetry-instrumentation-restify/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-restify/src/types.ts
  plugins/node/opentelemetry-instrumentation-restify/src/utils.ts
  plugins/node/opentelemetry-instrumentation-restify/src/version.ts
  plugins/node/opentelemetry-instrumentation-restify/test/restify.test.ts
  plugins/node/opentelemetry-instrumentation-restify/tsconfig.json
Labels: enhancement

#434 chore: clean up images from restify example
  examples/restify/images/jaeger-ui.png
  examples/restify/images/zipkin-ui.png
Labels: internal

#432 feat: pino instrumentation
  plugins/node/opentelemetry-instrumentation-pino/.eslintignore
  plugins/node/opentelemetry-instrumentation-pino/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-pino/.npmignore
  plugins/node/opentelemetry-instrumentation-pino/LICENSE
  plugins/node/opentelemetry-instrumentation-pino/README.md
  plugins/node/opentelemetry-instrumentation-pino/package.json
  plugins/node/opentelemetry-instrumentation-pino/src/index.ts
  plugins/node/opentelemetry-instrumentation-pino/src/pino.ts
  plugins/node/opentelemetry-instrumentation-pino/src/types.ts
  plugins/node/opentelemetry-instrumentation-pino/src/version.ts
  plugins/node/opentelemetry-instrumentation-pino/test/pino.test.ts
  plugins/node/opentelemetry-instrumentation-pino/tsconfig.json
Labels: enhancement

#454 chore: make aws generator public
  packages/opentelemetry-id-generator-aws-xray/package.json
Labels: internal

#455 Update gts, eslint, typescript and hapi dependencies
  detectors/node/opentelemetry-resource-detector-github/package.json
  metapackages/auto-instrumentations-node/package.json
  metapackages/auto-instrumentations-web/package.json
  package.json
  packages/opentelemetry-host-metrics/package.json
  packages/opentelemetry-id-generator-aws-xray/package.json
  packages/opentelemetry-test-utils/package.json
  plugins/node/opentelemetry-instrumentation-aws-lambda/package.json
  plugins/node/opentelemetry-instrumentation-bunyan/package.json
  plugins/node/opentelemetry-instrumentation-dns/package.json
  plugins/node/opentelemetry-instrumentation-express/package.json
  plugins/node/opentelemetry-instrumentation-graphql/package.json
  plugins/node/opentelemetry-instrumentation-hapi/package.json
  plugins/node/opentelemetry-instrumentation-ioredis/package.json
  plugins/node/opentelemetry-instrumentation-ioredis/src/types.ts
  plugins/node/opentelemetry-instrumentation-koa/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/package.json
  plugins/node/opentelemetry-instrumentation-mysql/package.json
  plugins/node/opentelemetry-instrumentation-net/package.json
  plugins/node/opentelemetry-instrumentation-pg/package.json
  plugins/node/opentelemetry-instrumentation-pino/package.json
  plugins/node/opentelemetry-instrumentation-redis/package.json
  plugins/node/opentelemetry-instrumentation-restify/package.json
  plugins/node/opentelemetry-instrumentation-winston/package.json
  plugins/web/opentelemetry-instrumentation-document-load/package.json
  plugins/web/opentelemetry-instrumentation-user-interaction/package.json
  plugins/web/opentelemetry-plugin-react-load/package.json
  propagators/opentelemetry-propagator-aws-xray/package.json
  propagators/opentelemetry-propagator-grpc-census-binary/package.json
  propagators/opentelemetry-propagator-ot-trace/package.json
Labels: depencies, internal

#450 chore: prefer use of global TracerProvider/MeterProvider
  metapackages/auto-instrumentations-node/README.md
  metapackages/auto-instrumentations-web/README.md
  plugins/node/opentelemetry-instrumentation-aws-lambda/README.md
  plugins/node/opentelemetry-instrumentation-bunyan/README.md
  plugins/node/opentelemetry-instrumentation-dns/README.md
  plugins/node/opentelemetry-instrumentation-express/README.md
  plugins/node/opentelemetry-instrumentation-graphql/README.md
  plugins/node/opentelemetry-instrumentation-hapi/README.md
  plugins/node/opentelemetry-instrumentation-ioredis/README.md
  plugins/node/opentelemetry-instrumentation-koa/README.md
  plugins/node/opentelemetry-instrumentation-mongodb/README.md
  plugins/node/opentelemetry-instrumentation-mysql/README.md
  plugins/node/opentelemetry-instrumentation-net/README.md
  plugins/node/opentelemetry-instrumentation-net/test/utils.ts
  plugins/node/opentelemetry-instrumentation-pg/README.md
  plugins/node/opentelemetry-instrumentation-pino/README.md
  plugins/node/opentelemetry-instrumentation-redis/README.md
  plugins/node/opentelemetry-instrumentation-restify/README.md
  plugins/node/opentelemetry-instrumentation-winston/README.md
  plugins/web/opentelemetry-instrumentation-document-load/README.md
  plugins/web/opentelemetry-instrumentation-user-interaction/README.md
  plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.nozone.test.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.test.ts
  propagators/opentelemetry-propagator-grpc-census-binary/README.md
Labels: documentation
