Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2021-05, with the labels that each got.

#441 feat(instrumentation-document-load): documentLoad attributes enhancement
  plugins/web/opentelemetry-instrumentation-document-load/src/documentLoad.ts
  plugins/web/opentelemetry-instrumentation-document-load/test/documentLoad.test.ts
Labels: enhancement

#471 Fix repository for pg
  plugins/node/opentelemetry-instrumentation-pg/package.json
Labels: express, internal

#472 docs: Explicitly state that express instrumentation does not export spans without http instrumentation
  plugins/node/opentelemetry-instrumentation-express/README.md
Labels: documentation, express

#470 chore: removing usage of timed event from api
  packages/opentelemetry-test-utils/testUtils.ts
  plugins/node/opentelemetry-instrumentation-pg/test/pg-pool.test.ts
  plugins/node/opentelemetry-instrumentation-pg/test/pg.test.ts
  plugins/node/opentelemetry-instrumentation-pg/test/types.ts
  plugins/web/opentelemetry-instrumentation-document-load/test/documentLoad.test.ts
Labels: enhancement

#481 fix: move faas_id and cloud_account_id to semantic conventions
  metapackages/auto-instrumentations-web/src/utils.ts
  metapackages/auto-instrumentations-web/test/utils.test.ts
  plugins/node/opentelemetry-instrumentation-aws-lambda/src/aws-lambda.ts
  plugins/node/opentelemetry-instrumentation-dns/test/functionals/utils.test.ts
  plugins/node/opentelemetry-instrumentation-express/src/express.ts
  plugins/node/opentelemetry-instrumentation-graphql/src/graphql.ts
  plugins/node/opentelemetry-instrumentation-graphql/src/types.ts
  plugins/node/opentelemetry-instrumentation-graphql/src/utils.ts
  plugins/node/opentelemetry-instrumentation-hapi/src/hapi.ts
  plugins/node/opentelemetry-instrumentation-ioredis/test/ioredis.test.ts
  plugins/node/opentelemetry-instrumentation-net/test/connect.test.ts
  plugins/node/opentelemetry-instrumentation-pg/src/pg.ts
  plugins/node/opentelemetry-instrumentation-pg/test/utils.test.ts
  plugins/node/opentelemetry-instrumentation-pino/test/pino.test.ts
  plugins/web/opentelemetry-instrumentation-document-load/src/documentLoad.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/src/userInteraction.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.test.ts
  propagators/opentelemetry-propagator-grpc-census-binary/src/GrpcCensusPropagator.ts
  propagators/opentelemetry-propagator-grpc-census-binary/test/BinaryTraceContext.test.ts
  propagators/opentelemetry-propagator-grpc-census-binary/test/GrpcCensusPropagator.test.ts
Labels: internal

#479 chore: generalize the instrumentation file name
  plugins/node/opentelemetry-instrumentation-aws-lambda/src/index.ts
  plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-aws-lambda/test/integrations/lambda-handler.test.ts
  plugins/node/opentelemetry-instrumentation-bunyan/src/index.ts
  plugins/node/opentelemetry-instrumentation-bunyan/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-bunyan/test/bunyan.test.ts
  plugins/node/opentelemetry-instrumentation-dns/src/index.ts
  plugins/node/opentelemetry-instrumentation-dns/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-dns/test/functionals/dns-disable.test.ts
  plugins/node/opentelemetry-instrumentation-dns/test/integrations/dns-lookup.test.ts
  plugins/node/opentelemetry-instrumentation-dns/test/integrations/dnspromise-lookup.test.ts
  plugins/node/opentelemetry-instrumentation-express/src/index.ts
  plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-express/src/types.ts
  plugins/node/opentelemetry-instrumentation-graphql/src/index.ts
  plugins/node/opentelemetry-instrumentation-graphql/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-hapi/src/index.ts
  plugins/node/opentelemetry-instrumentation-hapi/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-ioredis/src/index.ts
  plugins/node/opentelemetry-instrumentation-ioredis/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-ioredis/src/utils.ts
  plugins/node/opentelemetry-instrumentation-koa/src/index.ts
  plugins/node/opentelemetry-instrumentation-koa/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-mongodb/src/index.ts
  plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-mysql/src/index.ts
  plugins/node/opentelemetry-instrumentation-mysql/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-net/src/index.ts
  plugins/node/opentelemetry-instrumentation-net/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-net/test/connect.test.ts
  plugins/node/opentelemetry-instrumentation-net/test/instrument.test.ts
  plugins/node/opentelemetry-instrumentation-net/test/tls.test.ts
  plugins/node/opentelemetry-instrumentation-pg/src/index.ts
  plugins/node/opentelemetry-instrumentation-pg/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-pg/src/utils.ts
  plugins/node/opentelemetry-instrumentation-pino/src/index.ts
  plugins/node/opentelemetry-instrumentation-pino/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-pino/test/pino.test.ts
  plugins/node/opentelemetry-instrumentation-redis/src/index.ts
  plugins/node/opentelemetry-instrumentation-redis/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-redis/src/utils.ts
  plugins/node/opentelemetry-instrumentation-winston/src/index.ts
  plugins/node/opentelemetry-instrumentation-winston/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-winston/test/winston.test.ts
  plugins/web/opentelemetry-instrumentation-document-load/src/index.ts
  plugins/web/opentelemetry-instrumentation-document-load/src/instrumentation.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/src/index.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/src/instrumentation.ts
Labels: internal
