Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2021-11, with the labels that each got.

#723 chore: release main
  .release-please-manifest.json
  detectors/node/opentelemetry-resource-detector-aws/CHANGELOG.md
  detectors/node/opentelemetry-resource-detector-aws/package.json
Labels: autorelease: pending

#727 chore: release main
  .release-please-manifest.json
  metapackages/auto-instrumentations-node/CHANGELOG.md
  metapackages/auto-instrumentations-node/package.json
  plugins/node/opentelemetry-instrumentation-aws-sdk/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-aws-sdk/package.json
  plugins/node/opentelemetry-instrumentation-graphql/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-graphql/package.json
  plugins/node/opentelemetry-instrumentation-nestjs-core/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-nestjs-core/package.json
Labels: autorelease: pending

#734 chore: update graphql example to latest
  examples/graphql/docker/docker-compose.yaml
  examples/graphql/package.json
  examples/graphql/tracer.js
Labels: document

#716 ci: add markdown lint and fixed markdown files
  .github/workflows/lint.yml
  .markdownlint.json
  CONTRIBUTING.md
  README.md
  RELEASING.md
  examples/connect/README.md
  examples/dns/README.md
  examples/express/README.md
  examples/fastify/README.md
  examples/graphql/README.md
  examples/grpc-census-prop/README.md
  examples/grpc-census-prop/combination2.md
  examples/grpc-census-prop/combination4.md
  examples/grpc_dynamic_codegen/README.md
  examples/hapi/README.md
  examples/koa/README.md
  examples/mongodb/README.md
  examples/mysql/README.md
  examples/postgres/README.md
  examples/react-load/preact/README.md
  examples/react-load/react/README.md
  examples/redis/README.md
  metapackages/auto-instrumentations-node/README.md
  packages/opentelemetry-browser-extension-autoinjection/README.md
  packages/opentelemetry-host-metrics/README.md
  packages/opentelemetry-id-generator-aws-xray/README.md
  packages/opentelemetry-propagation-utils/README.md
  packages/opentelemetry-test-utils/README.md
  plugins/node/opentelemetry-instrumentation-aws-lambda/README.md
  plugins/node/opentelemetry-instrumentation-aws-sdk/doc/sns.md
  plugins/node/opentelemetry-instrumentation-connect/README.md
  plugins/node/opentelemetry-instrumentation-fastify/README.md
  plugins/node/opentelemetry-instrumentation-generic-pool/README.md
  plugins/node/opentelemetry-instrumentation-graphql/README.md
  plugins/node/opentelemetry-instrumentation-knex/README.md
  plugins/node/opentelemetry-instrumentation-mongodb/README.md
  plugins/node/opentelemetry-instrumentation-nestjs-core/README.md
  plugins/node/opentelemetry-instrumentation-router/README.md
  plugins/web/opentelemetry-plugin-react-load/README.md
  propagators/opentelemetry-propagator-aws-xray/README.md
Labels: internal

#748 chore: release main
  .release-please-manifest.json
  metapackages/auto-instrumentations-node/CHANGELOG.md
  metapackages/auto-instrumentations-node/package.json
  plugins/node/opentelemetry-instrumentation-aws-sdk/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-aws-sdk/package.json
  plugins/node/opentelemetry-instrumentation-koa/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-koa/package.json
  plugins/node/opentelemetry-instrumentation-pino/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-pino/package.json
Labels: autorelease: pending

#766 chore: release main
  .release-please-manifest.json
  plugins/node/opentelemetry-instrumentation-aws-sdk/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-aws-sdk/package.json
Labels: autorelease: pending
