Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2021-07, with the labels that each got.

#556 chore: update core and API
  detectors/node/opentelemetry-resource-detector-github/package.json
  examples/dns/package.json
  examples/express/package.json
  examples/graphql/package.json
  examples/grpc-census-prop/package.json
  examples/grpc_dynamic_codegen/package.json
  examples/hapi/package.json
  examples/host-metrics/package.json
  examples/ioredis/package.json
  examples/koa/package.json
  examples/memcached/package.json
  examples/meta-node/package.json
  examples/mongodb/package.json
  examples/mysql/package.json
  examples/network/package.json
  examples/postgres/package.json
  examples/react-load/preact/package.json
  examples/react-load/react/package.json
  examples/redis/package.json
  examples/restify/package.json
  examples/router/package.json
  examples/web/package.json
  metapackages/auto-instrumentations-node/package.json
  metapackages/auto-instrumentations-web/package.json
  packages/opentelemetry-host-metrics/package.json
  packages/opentelemetry-id-generator-aws-xray/package.json
  packages/opentelemetry-test-utils/package.json
  plugins/node/opentelemetry-instrumentation-aws-lambda/package.json
  plugins/node/opentelemetry-instrumentation-bunyan/package.json
  plugins/node/opentelemetry-instrumentation-cassandra/package.json
  plugins/node/opentelemetry-instrumentation-dns/package.json
  plugins/node/opentelemetry-instrumentation-express/package.json
  plugins/node/opentelemetry-instrumentation-generic-pool/package.json
  plugins/node/opentelemetry-instrumentation-graphql/package.json
  plugins/node/opentelemetry-instrumentation-hapi/package.json
  plugins/node/opentelemetry-instrumentation-ioredis/package.json
  plugins/node/opentelemetry-instrumentation-knex/package.json
  plugins/node/opentelemetry-instrumentation-koa/package.json
  plugins/node/opentelemetry-instrumentation-memcached/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/package.json
  plugins/node/opentelemetry-instrumentation-mysql/package.json
  plugins/node/opentelemetry-instrumentation-mysql2/package.json
  plugins/node/opentelemetry-instrumentation-net/package.json
  plugins/node/opentelemetry-instrumentation-pg/package.json
  plugins/node/opentelemetry-instrumentation-pino/package.json
  plugins/node/opentelemetry-instrumentation-redis/package.json
  plugins/node/opentelemetry-instrumentation-restify/package.json
  plugins/node/opentelemetry-instrumentation-router/package.json
  plugins/node/opentelemetry-instrumentation-winston/package.json
  plugins/web/opentelemetry-instrumentation-document-load/package.json
  plugins/web/opentelemetry-instrumentation-user-interaction/package.json
  plugins/web/opentelemetry-plugin-react-load/package.json
  propagators/opentelemetry-propagator-aws-xray/package.json
  propagators/opentelemetry-propagator-grpc-census-binary/package.json
  propagators/opentelemetry-propagator-ot-trace/package.json
Labels: dependencies, enhancement

#554 chore: remove unneeded ts-node dev-dependency
  plugins/node/opentelemetry-instrumentation-cassandra/package.json
  plugins/node/opentelemetry-instrumentation-pino/package.json
Labels: dependencies, internal

#557 chore: aligning target for esm build with core repo
  plugins/web/opentelemetry-instrumentation-document-load/src/instrumentation.ts
  tsconfig.base.esm.json
  tsconfig.es5.json
Labels: bug

#563 docs(auto-instrumentations-node): improved readme
  metapackages/auto-instrumentations-node/README.md
Labels: document

#549 chore: enable typescript 4.3 option noImplicitOverride
  .gitattributes
  plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-bunyan/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-dns/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-graphql/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-memcached/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-mysql/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-mysql2/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-net/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-pino/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-redis/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-winston/src/instrumentation.ts
  plugins/web/opentelemetry-instrumentation-document-load/src/instrumentation.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/src/instrumentation.ts
  plugins/web/opentelemetry-plugin-react-load/test/test-react-components/AllLifecycles.tsx
  plugins/web/opentelemetry-plugin-react-load/test/test-react-components/MissingComponentDidMount.tsx
  plugins/web/opentelemetry-plugin-react-load/test/test-react-components/MissingComponentDidUpdate.tsx
  plugins/web/opentelemetry-plugin-react-load/test/test-react-components/MissingGetSnapshotBeforeUpdate.tsx
  plugins/web/opentelemetry-plugin-react-load/test/test-react-components/MissingRender.tsx
  plugins/web/opentelemetry-plugin-react-load/test/test-react-components/MissingShouldComponentUpdate.tsx
  plugins/web/opentelemetry-plugin-react-load/test/test-react-components/ShouldComponentUpdateFalse.tsx
  tsconfig.base.json
Labels: internal

#566 feat(aws-lambda): added eventContextExtractor config option
  plugins/node/opentelemetry-instrumentation-aws-lambda/README.md
  plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-aws-lambda/src/types.ts
  plugins/node/opentelemetry-instrumentation-aws-lambda/test/integrations/lambda-handler.test.ts
Labels: enhancement

#569 docs(instrumentation-graphql): improve README.md
  examples/graphql/package.json
  plugins/node/opentelemetry-instrumentation-graphql/README.md
Labels: document

#573 chore: fixing express example
  examples/express/package.json
  examples/express/tracer.js
Labels: bug

#571 fix(instrumentation-hapi): change root span name to route name
  plugins/node/opentelemetry-instrumentation-hapi/package.json
  plugins/node/opentelemetry-instrumentation-hapi/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-hapi/src/utils.ts
  plugins/node/opentelemetry-instrumentation-hapi/test/hapi.test.ts
Labels: enhancement

#570 fix(package.json): publish source maps
  packages/opentelemetry-host-metrics/package.json
  plugins/node/opentelemetry-instrumentation-aws-lambda/package.json
  plugins/node/opentelemetry-instrumentation-bunyan/package.json
  plugins/node/opentelemetry-instrumentation-cassandra/package.json
  plugins/node/opentelemetry-instrumentation-dns/package.json
  plugins/node/opentelemetry-instrumentation-express/package.json
  plugins/node/opentelemetry-instrumentation-generic-pool/package.json
  plugins/node/opentelemetry-instrumentation-hapi/package.json
  plugins/node/opentelemetry-instrumentation-ioredis/package.json
  plugins/node/opentelemetry-instrumentation-knex/package.json
  plugins/node/opentelemetry-instrumentation-koa/package.json
  plugins/node/opentelemetry-instrumentation-memcached/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/package.json
  plugins/node/opentelemetry-instrumentation-mysql/package.json
  plugins/node/opentelemetry-instrumentation-mysql2/package.json
  plugins/node/opentelemetry-instrumentation-net/package.json
  plugins/node/opentelemetry-instrumentation-pg/package.json
  plugins/node/opentelemetry-instrumentation-pino/package.json
  plugins/node/opentelemetry-instrumentation-redis/package.json
  plugins/node/opentelemetry-instrumentation-restify/package.json
  plugins/node/opentelemetry-instrumentation-router/package.json
  plugins/node/opentelemetry-instrumentation-winston/package.json
  propagators/opentelemetry-propagator-grpc-census-binary/package.json
Labels: enhancement

#576 chore: update otel dependencies
  examples/dns/package.json
  examples/express/package.json
  examples/graphql/package.json
  examples/grpc-census-prop/package.json
  examples/grpc_dynamic_codegen/package.json
  examples/hapi/package.json
  examples/host-metrics/package.json
  examples/ioredis/package.json
  examples/koa/package.json
  examples/memcached/package.json
  examples/meta-node/package.json
  examples/mongodb/package.json
  examples/mysql/package.json
  examples/network/package.json
  examples/postgres/package.json
  examples/react-load/preact/package.json
  examples/react-load/react/package.json
  examples/redis/package.json
  examples/restify/package.json
  examples/router/package.json
  examples/web/package.json
  packages/opentelemetry-browser-extension-autoinjection/package.json
Labels: dependencies

#583 style: use single quotes everywhere and add a rule to eslint
  eslint.config.js
  metapackages/auto-instrumentations-web/README.md
  plugins/node/opentelemetry-instrumentation-ioredis/README.md
  propagators/opentelemetry-propagator-grpc-census-binary/README.md
  scripts/version-update.js
Labels: internal

#592 chore(deps): upgrade @types/pino to be compatible with latest sonic-stream types
  plugins/node/opentelemetry-instrumentation-pino/package.json
Labels: internal

#594 chore: update core deps to 0.24.0
  detectors/node/opentelemetry-resource-detector-github/package.json
  examples/dns/package.json
  examples/express/package.json
  examples/express/tracer.js
  examples/graphql/package.json
  examples/grpc-census-prop/package.json
  examples/grpc_dynamic_codegen/package.json
  examples/hapi/package.json
  examples/host-metrics/package.json
  examples/ioredis/package.json
  examples/koa/package.json
  examples/memcached/package.json
  examples/memcached/tracer.js
  examples/meta-node/package.json
  examples/mongodb/package.json
  examples/mysql/package.json
  examples/network/package.json
  examples/postgres/package.json
  examples/react-load/preact/package.json
  examples/react-load/react/package.json
  examples/redis/package.json
  examples/restify/package.json
  examples/router/package.json
  examples/web/package.json
  metapackages/auto-instrumentations-node/README.md
  metapackages/auto-instrumentations-node/package.json
  metapackages/auto-instrumentations-web/package.json
  packages/opentelemetry-browser-extension-autoinjection/package.json
  packages/opentelemetry-browser-extension-autoinjection/src/instrumentation/index.ts
  packages/opentelemetry-host-metrics/package.json
  packages/opentelemetry-id-generator-aws-xray/package.json
  packages/opentelemetry-test-utils/package.json
  plugins/node/opentelemetry-instrumentation-aws-lambda/package.json
  plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-aws-lambda/test/integrations/lambda-handler.test.ts
  plugins/node/opentelemetry-instrumentation-bunyan/package.json
  plugins/node/opentelemetry-instrumentation-cassandra/package.json
  plugins/node/opentelemetry-instrumentation-dns/package.json
  plugins/node/opentelemetry-instrumentation-express/package.json
  plugins/node/opentelemetry-instrumentation-generic-pool/package.json
  plugins/node/opentelemetry-instrumentation-graphql/package.json
  plugins/node/opentelemetry-instrumentation-hapi/package.json
  plugins/node/opentelemetry-instrumentation-ioredis/package.json
  plugins/node/opentelemetry-instrumentation-knex/package.json
  plugins/node/opentelemetry-instrumentation-koa/package.json
  plugins/node/opentelemetry-instrumentation-memcached/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/package.json
  plugins/node/opentelemetry-instrumentation-mysql/package.json
  plugins/node/opentelemetry-instrumentation-mysql2/package.json
  plugins/node/opentelemetry-instrumentation-net/package.json
  plugins/node/opentelemetry-instrumentation-pg/package.json
  plugins/node/opentelemetry-instrumentation-pino/package.json
  plugins/node/opentelemetry-instrumentation-redis/package.json
  plugins/node/opentelemetry-instrumentation-restify/package.json
  plugins/node/opentelemetry-instrumentation-router/package.json
  plugins/node/opentelemetry-instrumentation-winston/package.json
  plugins/web/opentelemetry-instrumentation-document-load/package.json
  plugins/web/opentelemetry-instrumentation-user-interaction/package.json
  plugins/web/opentelemetry-plugin-react-load/package.json
  propagators/opentelemetry-propagator-aws-xray/package.json
Labels: enhancement

#601 chore: configure renovate to bump API
  renovate.json
Labels: internal
