Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2021-01, with the labels that each got.

#298 Add CodeQL Security Scans
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#273 feat: enable root span route instrumentation without any express layer spans
  plugins/node/opentelemetry-plugin-express/package.json
  plugins/node/opentelemetry-plugin-express/src/express.ts
  plugins/node/opentelemetry-plugin-express/src/types.ts
  plugins/node/opentelemetry-plugin-express/test/express.test.ts
Labels: enhancement

#300 chore: fixing async resolvers for graphql
  plugins/node/opentelemetry-instrumentation-graphql/src/utils.ts
  plugins/node/opentelemetry-instrumentation-graphql/test/graphql.test.ts
Labels: bug

#299 chore: fixing parent span for graphql
  examples/graphql/docker/docker-compose.yaml
  plugins/node/opentelemetry-instrumentation-graphql/src/graphql.ts
  plugins/node/opentelemetry-instrumentation-graphql/src/symbols.ts
  plugins/node/opentelemetry-instrumentation-graphql/src/types.ts
  plugins/node/opentelemetry-instrumentation-graphql/test/graphql.test.ts
Labels: bug

#322 Fix link
  README.md
Labels: bug

#239 fix(plugin-ioredis): end span on response from the server and set span status according to response
  packages/opentelemetry-test-utils/testUtils.ts
  plugins/node/opentelemetry-plugin-ioredis/src/utils.ts
  plugins/node/opentelemetry-plugin-ioredis/test/ioredis.test.ts
Labels: bug

#325 chore: change links to point to main
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/plugin_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/lint.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  RELEASING.md
  examples/dns/README.md
  examples/express/README.md
  examples/graphql/README.md
  examples/graphql/schema.js
  examples/grpc-census-prop/README.md
  examples/grpc_dynamic_codegen/README.md
  examples/hapi/README.md
  examples/koa/README.md
  examples/mongodb/README.md
  examples/mysql/README.md
  examples/postgres/README.md
  examples/react-load/preact/README.md
  examples/react-load/react/README.md
  examples/redis/README.md
  metapackages/plugins-node-core-and-contrib/README.md
  packages/opentelemetry-host-metrics/README.md
  plugins/node/opentelemetry-hapi-instrumentation/README.md
  plugins/node/opentelemetry-hapi-instrumentation/src/hapi.ts
  plugins/node/opentelemetry-instrumentation-graphql/README.md
  plugins/node/opentelemetry-instrumentation-graphql/test/schema.ts
  plugins/node/opentelemetry-koa-instrumentation/README.md
  plugins/node/opentelemetry-plugin-dns/README.md
  plugins/node/opentelemetry-plugin-express/README.md
  plugins/node/opentelemetry-plugin-express/src/types.ts
  plugins/node/opentelemetry-plugin-ioredis/README.md
  plugins/node/opentelemetry-plugin-ioredis/src/types.ts
  plugins/node/opentelemetry-plugin-mongodb/README.md
  plugins/node/opentelemetry-plugin-mongodb/src/types.ts
  plugins/node/opentelemetry-plugin-mysql/README.md
  plugins/node/opentelemetry-plugin-pg-pool/README.md
  plugins/node/opentelemetry-plugin-pg-pool/src/enums.ts
  plugins/node/opentelemetry-plugin-pg/README.md
  plugins/node/opentelemetry-plugin-pg/src/enums.ts
  plugins/node/opentelemetry-plugin-redis/README.md
  plugins/web/opentelemetry-plugin-document-load/README.md
  plugins/web/opentelemetry-plugin-react-load/README.md
  plugins/web/opentelemetry-plugin-user-interaction/README.md
  plugins/web/opentelemetry-plugin-user-interaction/test/userInteraction.nozone.test.ts
  plugins/web/opentelemetry-plugin-user-interaction/test/userInteraction.test.ts
  propagators/README.md
  propagators/opentelemetry-propagator-grpc-census-binary/README.md
  propagators/opentelemetry-propagator-jaeger/README.md
Labels: documentation

#318 feat: OpenTracing propagator
  propagators/opentelemetry-propagator-opentracing/.eslintignore
  propagators/opentelemetry-propagator-opentracing/.eslintrc.js
  propagators/opentelemetry-propagator-opentracing/.npmignore
  propagators/opentelemetry-propagator-opentracing/LICENSE
  propagators/opentelemetry-propagator-opentracing/README.md
  propagators/opentelemetry-propagator-opentracing/karma.conf.js
  propagators/opentelemetry-propagator-opentracing/package.json
  propagators/opentelemetry-propagator-opentracing/src/OpenTracingPropagator.ts
  propagators/opentelemetry-propagator-opentracing/src/index.ts
  propagators/opentelemetry-propagator-opentracing/src/version.ts
  propagators/opentelemetry-propagator-opentracing/test/OpenTracingPropagator.test.ts
  propagators/opentelemetry-propagator-opentracing/test/index-webpack.ts
  propagators/opentelemetry-propagator-opentracing/tsconfig.json
Labels: enhancement
