Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2021-03, with the labels that each got.

#371 chore: bump core to 0.18
  detectors/node/opentelemetry-resource-detector-github/package.json
  examples/dns/package.json
  examples/express/package.json
  examples/graphql/package.json
  examples/grpc-census-prop/package.json
  examples/hapi/package.json
  examples/host-metrics/package.json
  examples/ioredis/package.json
  examples/koa/package.json
  examples/mongodb/package.json
  examples/mysql/package.json
  examples/postgres/package.json
  examples/react-load/preact/package.json
  examples/react-load/react/package.json
  examples/redis/package.json
  examples/web/package.json
  metapackages/plugins-node-core-and-contrib/package.json
  packages/opentelemetry-host-metrics/package.json
  packages/opentelemetry-test-utils/package.json
  plugins/node/opentelemetry-hapi-instrumentation/package.json
  plugins/node/opentelemetry-instrumentation-dns/package.json
  plugins/node/opentelemetry-instrumentation-express/package.json
  plugins/node/opentelemetry-instrumentation-graphql/package.json
  plugins/node/opentelemetry-instrumentation-ioredis/package.json
  plugins/node/opentelemetry-instrumentation-koa/package.json
  plugins/node/opentelemetry-instrumentation-pg/package.json
  plugins/node/opentelemetry-plugin-dns/package.json
  plugins/node/opentelemetry-plugin-express/package.json
  plugins/node/opentelemetry-plugin-ioredis/package.json
  plugins/node/opentelemetry-plugin-mongodb/package.json
  plugins/node/opentelemetry-plugin-mysql/package.json
  plugins/node/opentelemetry-plugin-pg-pool/package.json
  plugins/node/opentelemetry-plugin-pg/package.json
  plugins/node/opentelemetry-plugin-redis/package.json
  plugins/web/opentelemetry-instrumentation-document-load/package.json
  plugins/web/opentelemetry-instrumentation-user-interaction/package.json
  plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.test.ts
  plugins/web/opentelemetry-plugin-react-load/package.json
  propagators/opentelemetry-propagator-grpc-census-binary/package.json
  propagators/opentelemetry-propagator-jaeger/package.json
  propagators/opentelemetry-propagator-ot-trace/package.json
Labels: internal

#381 chore: fixing the graphql example and allowing support version of graph from ver 14
  examples/graphql/tracer.js
  plugins/node/opentelemetry-instrumentation-graphql/src/graphql.ts
  plugins/node/opentelemetry-instrumentation-graphql/src/types.ts
  plugins/node/opentelemetry-instrumentation-graphql/src/utils.ts
Labels: enhancement

#354 refactor: migrate mongodb to instrumentation #250
  plugins/node/opentelemetry-instrumentation-mongodb/.eslintignore
  plugins/node/opentelemetry-instrumentation-mongodb/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-mongodb/.npmignore
  plugins/node/opentelemetry-instrumentation-mongodb/LICENSE
  plugins/node/opentelemetry-instrumentation-mongodb/README.md
  plugins/node/opentelemetry-instrumentation-mongodb/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/src/index.ts
  plugins/node/opentelemetry-instrumentation-mongodb/src/mongodb.ts
  plugins/node/opentelemetry-instrumentation-mongodb/src/types.ts
  plugins/node/opentelemetry-instrumentation-mongodb/src/version.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb.test.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/utils.ts
  plugins/node/opentelemetry-instrumentation-mongodb/tsconfig.json
Labels: enhancement

#380 Moving Hapi Plugin to Instrumentation
  examples/hapi/package.json
  examples/hapi/server.js
  examples/hapi/tracer.js
  plugins/node/opentelemetry-instrumentation-hapi/.eslintignore
  plugins/node/opentelemetry-instrumentation-hapi/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-hapi/.mocharc.js
  plugins/node/opentelemetry-instrumentation-hapi/.npmignore
  plugins/node/opentelemetry-instrumentation-hapi/LICENSE
  plugins/node/opentelemetry-instrumentation-hapi/README.md
  plugins/node/opentelemetry-instrumentation-hapi/package.json
  plugins/node/opentelemetry-instrumentation-hapi/src/hapi.ts
  plugins/node/opentelemetry-instrumentation-hapi/src/index.ts
  plugins/node/opentelemetry-instrumentation-hapi/src/types.ts
  plugins/node/opentelemetry-instrumentation-hapi/src/utils.ts
  plugins/node/opentelemetry-instrumentation-hapi/src/version.ts
  plugins/node/opentelemetry-instrumentation-hapi/test/hapi-plugin.test.ts
  plugins/node/opentelemetry-instrumentation-hapi/test/hapi-server-ext.test.ts
  plugins/node/opentelemetry-instrumentation-hapi/test/hapi.test.ts
  plugins/node/opentelemetry-instrumentation-hapi/test/plugin.ts
  plugins/node/opentelemetry-instrumentation-hapi/test/testPackage.json
  plugins/node/opentelemetry-instrumentation-hapi/tsconfig.json
Labels: enhancement

#373 Update README.md
  packages/opentelemetry-host-metrics/README.md
Labels: documentation

#389 feat: net module instrumentation
  plugins/node/opentelemetry-instrumentation-net/.eslintignore
  plugins/node/opentelemetry-instrumentation-net/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-net/.npmignore
  plugins/node/opentelemetry-instrumentation-net/LICENSE
  plugins/node/opentelemetry-instrumentation-net/README.md
  plugins/node/opentelemetry-instrumentation-net/package.json
  plugins/node/opentelemetry-instrumentation-net/src/index.ts
  plugins/node/opentelemetry-instrumentation-net/src/net.ts
  plugins/node/opentelemetry-instrumentation-net/src/types.ts
  plugins/node/opentelemetry-instrumentation-net/src/utils.ts
  plugins/node/opentelemetry-instrumentation-net/src/version.ts
  plugins/node/opentelemetry-instrumentation-net/test/connect.test.ts
  plugins/node/opentelemetry-instrumentation-net/test/instrument.test.ts
  plugins/node/opentelemetry-instrumentation-net/test/utils.ts
  plugins/node/opentelemetry-instrumentation-net/tsconfig.json
Labels: enhancement

#327 feat: enable root span to contain route
  plugins/node/opentelemetry-instrumentation-koa/src/koa.ts
  plugins/node/opentelemetry-instrumentation-koa/test/koa.test.ts
Labels: enhancement

#392 chore: fixing broken links
  propagators/opentelemetry-propagator-grpc-census-binary/README.md
  propagators/opentelemetry-propagator-jaeger/README.md
  propagators/opentelemetry-propagator-ot-trace/README.md
Labels: internal

#393 feat: mysql instrumentation
  metapackages/auto-instrumentations-node/package.json
  metapackages/auto-instrumentations-node/src/utils.ts
  metapackages/auto-instrumentations-node/test/utils.test.ts
  plugins/node/opentelemetry-instrumentation-mysql/.eslintignore
  plugins/node/opentelemetry-instrumentation-mysql/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-mysql/.npmignore
  plugins/node/opentelemetry-instrumentation-mysql/LICENSE
  plugins/node/opentelemetry-instrumentation-mysql/README.md
  plugins/node/opentelemetry-instrumentation-mysql/package.json
  plugins/node/opentelemetry-instrumentation-mysql/src/index.ts
  plugins/node/opentelemetry-instrumentation-mysql/src/mysql.ts
  plugins/node/opentelemetry-instrumentation-mysql/src/types.ts
  plugins/node/opentelemetry-instrumentation-mysql/src/utils.ts
  plugins/node/opentelemetry-instrumentation-mysql/src/version.ts
  plugins/node/opentelemetry-instrumentation-mysql/test/mysql.test.ts
  plugins/node/opentelemetry-instrumentation-mysql/tsconfig.json
Labels: enhancement

#391 chore: adding meta package for web
  examples/web/examples/meta/index.html
  examples/web/examples/meta/index.js
  examples/web/package.json
  examples/web/webpack.config.js
  metapackages/auto-instrumentations-node/README.md
  metapackages/auto-instrumentations-web/.eslintignore
  metapackages/auto-instrumentations-web/.eslintrc.js
  metapackages/auto-instrumentations-web/.npmignore
  metapackages/auto-instrumentations-web/LICENSE
  metapackages/auto-instrumentations-web/README.md
  metapackages/auto-instrumentations-web/karma.conf.js
  metapackages/auto-instrumentations-web/package.json
  metapackages/auto-instrumentations-web/src/index.ts
  metapackages/auto-instrumentations-web/src/utils.ts
  metapackages/auto-instrumentations-web/test/index-webpack.ts
  metapackages/auto-instrumentations-web/test/utils.test.ts
  metapackages/auto-instrumentations-web/tsconfig.json
  plugins/web/opentelemetry-instrumentation-document-load/src/documentLoad.ts
Labels: enhancement

#395 chore: fixing broken links, updating to correct base url, replacing gitter with github discussions
  README.md
  metapackages/auto-instrumentations-node/README.md
  metapackages/plugins-node-core-and-contrib/README.md
  packages/opentelemetry-host-metrics/README.md
  plugins/node/opentelemetry-instrumentation-dns/README.md
  plugins/node/opentelemetry-instrumentation-express/README.md
  plugins/node/opentelemetry-instrumentation-graphql/README.md
  plugins/node/opentelemetry-instrumentation-hapi/README.md
  plugins/node/opentelemetry-instrumentation-ioredis/README.md
  plugins/node/opentelemetry-instrumentation-koa/README.md
  plugins/node/opentelemetry-instrumentation-mongodb/README.md
  plugins/node/opentelemetry-instrumentation-mysql/README.md
  plugins/node/opentelemetry-instrumentation-net/README.md
  plugins/node/opentelemetry-instrumentation-pg/README.md
  plugins/node/opentelemetry-instrumentation-redis/README.md
  plugins/node/opentelemetry-plugin-dns/README.md
  plugins/node/opentelemetry-plugin-express/README.md
  plugins/node/opentelemetry-plugin-ioredis/README.md
  plugins/node/opentelemetry-plugin-mongodb/README.md
  plugins/node/opentelemetry-plugin-mysql/README.md
  plugins/node/opentelemetry-plugin-pg-pool/README.md
  plugins/node/opentelemetry-plugin-pg/README.md
  plugins/node/opentelemetry-plugin-redis/README.md
  plugins/web/opentelemetry-instrumentation-document-load/README.md
  plugins/web/opentelemetry-instrumentation-user-interaction/README.md
  plugins/web/opentelemetry-plugin-react-load/README.md
  propagators/opentelemetry-propagator-grpc-census-binary/README.md
  propagators/opentelemetry-propagator-jaeger/README.md
  propagators/opentelemetry-propagator-ot-trace/README.md
Labels: enhancement
