Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2021-08, with the labels that each got.

#593 feat: move aws/gcp detectors from opentelemetry-js repo
  detectors/node/opentelemetry-resource-detector-aws/.eslintignore
  detectors/node/opentelemetry-resource-detector-aws/.eslintrc.js
  detectors/node/opentelemetry-resource-detector-aws/.npmignore
  detectors/node/opentelemetry-resource-detector-aws/LICENSE
  detectors/node/opentelemetry-resource-detector-aws/README.md
  detectors/node/opentelemetry-resource-detector-aws/package.json
  detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsBeanstalkDetector.ts
  detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEc2Detector.ts
  detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEcsDetector.ts
  detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetector.ts
  detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsLambdaDetector.ts
  detectors/node/opentelemetry-resource-detector-aws/src/detectors/index.ts
  detectors/node/opentelemetry-resource-detector-aws/src/index.ts
  detectors/node/opentelemetry-resource-detector-aws/src/version.ts
  detectors/node/opentelemetry-resource-detector-aws/test/detectors/AwsBeanstalkDetector.test.ts
  detectors/node/opentelemetry-resource-detector-aws/test/detectors/AwsEc2Detector.test.ts
  detectors/node/opentelemetry-resource-detector-aws/test/detectors/AwsEcsDetector.test.ts
  detectors/node/opentelemetry-resource-detector-aws/test/detectors/AwsEksDetector.test.ts
  detectors/node/opentelemetry-resource-detector-aws/test/detectors/AwsLambdaDetector.test.ts
  detectors/node/opentelemetry-resource-detector-aws/tsconfig.json
  detectors/node/opentelemetry-resource-detector-gcp/.eslintignore
  detectors/node/opentelemetry-resource-detector-gcp/.eslintrc.js
  detectors/node/opentelemetry-resource-detector-gcp/.npmignore
  detectors/node/opentelemetry-resource-detector-gcp/LICENSE
  detectors/node/opentelemetry-resource-detector-gcp/README.md
  detectors/node/opentelemetry-resource-detector-gcp/package.json
  detectors/node/opentelemetry-resource-detector-gcp/src/detectors/GcpDetector.ts
  detectors/node/opentelemetry-resource-detector-gcp/src/detectors/index.ts
  detectors/node/opentelemetry-resource-detector-gcp/src/index.ts
  detectors/node/opentelemetry-resource-detector-gcp/src/version.ts
  detectors/node/opentelemetry-resource-detector-gcp/test/detectors/GcpDetector.test.ts
  detectors/node/opentelemetry-resource-detector-gcp/tsconfig.json
  packages/opentelemetry-test-utils/index.ts
  packages/opentelemetry-test-utils/package.json
  packages/opentelemetry-test-utils/resource-assertions.ts
  packages/opentelemetry-test-utils/test-utils.ts
Labels: enhancement

#580 fix: redis instrumentation loses context when using callbacks
  plugins/node/opentelemetry-instrumentation-redis/src/utils.ts
  plugins/node/opentelemetry-instrumentation-redis/test/redis.test.ts
Labels: bug

#606 chore: add ownership for aws propagator
  .github/component_owners.yml
  .github/workflows/component-owners.yml
Labels: internal

#596 docs(test-utils): add README.md for @opentelemetry/test-utils
  packages/opentelemetry-test-utils/README.md
  packages/opentelemetry-test-utils/package.json
Labels: internal

#597 chore: add script to update core dependencies
  scripts/update-core-deps.js
Labels: internal

#589 fix(hapi-instrumentation): close spans on errors in instrumented functions
  plugins/node/opentelemetry-instrumentation-hapi/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-hapi/test/hapi-server-ext.test.ts
  plugins/node/opentelemetry-instrumentation-hapi/test/hapi.test.ts
Labels: bug

#588 chore: adding instrumentation for connect
  examples/connect/README.md
  examples/connect/client.js
  examples/connect/docker/collector-config.yaml
  examples/connect/docker/docker-compose.yaml
  examples/connect/images/trace1.png
  examples/connect/package.json
  examples/connect/server.js
  examples/connect/tracing.js
  plugins/node/opentelemetry-instrumentation-connect/.eslintignore
  plugins/node/opentelemetry-instrumentation-connect/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-connect/.npmignore
  plugins/node/opentelemetry-instrumentation-connect/LICENSE
  plugins/node/opentelemetry-instrumentation-connect/README.md
  plugins/node/opentelemetry-instrumentation-connect/package.json
  plugins/node/opentelemetry-instrumentation-connect/src/enums/AttributeNames.ts
  plugins/node/opentelemetry-instrumentation-connect/src/index.ts
  plugins/node/opentelemetry-instrumentation-connect/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-connect/src/types.ts
  plugins/node/opentelemetry-instrumentation-connect/src/version.ts
  plugins/node/opentelemetry-instrumentation-connect/test/instrumentation.test.ts
  plugins/node/opentelemetry-instrumentation-connect/tsconfig.json
Labels: enhancement

#612 chore: ignore renovate-bot for component owners
  .github/component_owners.yml
Labels: internal

#615 docs: correct the build instructions
  packages/opentelemetry-browser-extension-autoinjection/README.md
Labels: documentation

#614 ci: speed up PR unit-test run time
  .github/workflows/unit-test.yml
  package.json
Labels: internal

#553 feat: Add NestJS instrumentation
  .github/component_owners.yml
  plugins/node/opentelemetry-instrumentation-nestjs-core/.eslintignore
  plugins/node/opentelemetry-instrumentation-nestjs-core/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-nestjs-core/.npmignore
  plugins/node/opentelemetry-instrumentation-nestjs-core/LICENSE
  plugins/node/opentelemetry-instrumentation-nestjs-core/README.md
  plugins/node/opentelemetry-instrumentation-nestjs-core/package.json
  plugins/node/opentelemetry-instrumentation-nestjs-core/scripts/test-all-versions
  plugins/node/opentelemetry-instrumentation-nestjs-core/src/enums/AttributeNames.ts
  plugins/node/opentelemetry-instrumentation-nestjs-core/src/enums/NestType.ts
  plugins/node/opentelemetry-instrumentation-nestjs-core/src/enums/index.ts
  plugins/node/opentelemetry-instrumentation-nestjs-core/src/index.ts
  plugins/node/opentelemetry-instrumentation-nestjs-core/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-nestjs-core/src/version.ts
  plugins/node/opentelemetry-instrumentation-nestjs-core/test/index.test.ts
  plugins/node/opentelemetry-instrumentation-nestjs-core/test/setup.ts
  plugins/node/opentelemetry-instrumentation-nestjs-core/tsconfig.json
Labels: enhancement

#648 ci: speed up lint workflow with hoisting
  .github/workflows/lint.yml
Labels: internal

#641 chore(mysql2): adding TAV script
  packages/opentelemetry-test-utils/test-utils.ts
  plugins/node/opentelemetry-instrumentation-mysql2/.tav.yml
  plugins/node/opentelemetry-instrumentation-mysql2/package.json
  plugins/node/opentelemetry-instrumentation-mysql2/test/mysql.test.ts
Labels: internal

#610 doc: add detectors section to readme
  README.md
Labels: document

#626 feat(mongodb): add db statement serializer config
  plugins/node/opentelemetry-instrumentation-mongodb/README.md
  plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-mongodb/src/types.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb.test.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/utils.ts
Labels: enhancement

#643 fix(user-interaction): event listeners have wrong this when listening for bubbled events
  plugins/web/opentelemetry-instrumentation-user-interaction/src/instrumentation.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.nozone.test.ts
Labels: bug

#619 fix: GraphQL throws TypeError: Cannot read property 'startToken' of undefined
  examples/graphql/README.md
  examples/graphql/client-federation.js
  examples/graphql/countries-service.js
  examples/graphql/package.json
  examples/graphql/server-federation.js
  package.json
  plugins/node/opentelemetry-instrumentation-graphql/src/utils.ts
Labels: bug
