Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2021-06, with the labels that each got.

#488 fix: dns plugin remove hostname attribute
  plugins/node/opentelemetry-instrumentation-dns/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-dns/test/utils/assertSpan.ts
Labels: bug

#517 feat: use rpcMetadata to update http span name #464
  plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-express/src/types.ts
  plugins/node/opentelemetry-instrumentation-express/test/custom-config.test.ts
  plugins/node/opentelemetry-instrumentation-express/test/express.test.ts
  plugins/node/opentelemetry-instrumentation-express/test/ignore-all.test.ts
  plugins/node/opentelemetry-instrumentation-koa/package.json
  plugins/node/opentelemetry-instrumentation-koa/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-koa/test/koa.test.ts
  plugins/node/opentelemetry-instrumentation-restify/package.json
  plugins/node/opentelemetry-instrumentation-restify/src/constants.ts
  plugins/node/opentelemetry-instrumentation-restify/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-restify/src/types.ts
  plugins/node/opentelemetry-instrumentation-restify/test/restify.test.ts
Labels: enhancement

#506 feat: knex instrumentation
  plugins/node/opentelemetry-instrumentation-knex/.eslintignore
  plugins/node/opentelemetry-instrumentation-knex/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-knex/.npmignore
  plugins/node/opentelemetry-instrumentation-knex/LICENSE
  plugins/node/opentelemetry-instrumentation-knex/README.md
  plugins/node/opentelemetry-instrumentation-knex/package.json
  plugins/node/opentelemetry-instrumentation-knex/src/constants.ts
  plugins/node/opentelemetry-instrumentation-knex/src/index.ts
  plugins/node/opentelemetry-instrumentation-knex/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-knex/src/types.ts
  plugins/node/opentelemetry-instrumentation-knex/src/utils.ts
  plugins/node/opentelemetry-instrumentation-knex/src/version.ts
  plugins/node/opentelemetry-instrumentation-knex/test/index.test.ts
  plugins/node/opentelemetry-instrumentation-knex/tsconfig.json
Labels: enhancement

#529 chore: update core and api to 0.21.0
  detectors/node/opentelemetry-resource-detector-github/package.json
  examples/dns/package.json
  examples/express/package.json
  examples/graphql/package.json
  examples/grpc-census-prop/package.json
  examples/grpc_dynamic_codegen/package.json
  examples/hapi/package.json
  examples/host-metrics/package.json
  examples/ioredis/package.json
  examples/koa/package.json
  examples/meta-node/package.json
  examples/mongodb/package.json
  examples/mysql/package.json
  examples/network/package.json
  examples/postgres/package.json
  examples/react-load/preact/package.json
  examples/react-load/react/package.json
  examples/redis/package.json
  examples/restify/package.json
  examples/router/package.json
  examples/web/package.json
  metapackages/auto-instrumentations-node/package.json
  metapackages/auto-instrumentations-web/package.json
  packages/opentelemetry-host-metrics/package.json
  packages/opentelemetry-id-generator-aws-xray/package.json
  packages/opentelemetry-test-utils/package.json
  plugins/node/opentelemetry-instrumentation-aws-lambda/package.json
  plugins/node/opentelemetry-instrumentation-bunyan/package.json
  plugins/node/opentelemetry-instrumentation-bunyan/test/bunyan.test.ts
  plugins/node/opentelemetry-instrumentation-dns/package.json
  plugins/node/opentelemetry-instrumentation-express/package.json
  plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-generic-pool/package.json
  plugins/node/opentelemetry-instrumentation-graphql/package.json
  plugins/node/opentelemetry-instrumentation-hapi/package.json
  plugins/node/opentelemetry-instrumentation-ioredis/package.json
  plugins/node/opentelemetry-instrumentation-knex/package.json
  plugins/node/opentelemetry-instrumentation-koa/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/package.json
  plugins/node/opentelemetry-instrumentation-mysql/package.json
  plugins/node/opentelemetry-instrumentation-net/package.json
  plugins/node/opentelemetry-instrumentation-pg/package.json
  plugins/node/opentelemetry-instrumentation-pg/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-pino/package.json
  plugins/node/opentelemetry-instrumentation-pino/test/pino.test.ts
  plugins/node/opentelemetry-instrumentation-redis/package.json
  plugins/node/opentelemetry-instrumentation-redis/src/utils.ts
  plugins/node/opentelemetry-instrumentation-restify/package.json
  plugins/node/opentelemetry-instrumentation-router/package.json
  plugins/node/opentelemetry-instrumentation-router/test/index.test.ts
  plugins/node/opentelemetry-instrumentation-winston/package.json
  plugins/node/opentelemetry-instrumentation-winston/test/winston.test.ts
  plugins/web/opentelemetry-instrumentation-document-load/package.json
  plugins/web/opentelemetry-instrumentation-user-interaction/package.json
  plugins/web/opentelemetry-plugin-react-load/package.json
  propagators/opentelemetry-propagator-aws-xray/package.json
  propagators/opentelemetry-propagator-grpc-census-binary/package.json
  propagators/opentelemetry-propagator-ot-trace/package.json
Labels: depencies, enhancement

#539 feat: memcached instrumentation
  .github/workflows/unit-test.yml
  examples/memcached/README.md
  examples/memcached/index.js
  examples/memcached/package.json
  examples/memcached/tracer.js
  packages/opentelemetry-test-utils/testUtils.ts
  plugins/node/opentelemetry-instrumentation-memcached/.eslintignore
  plugins/node/opentelemetry-instrumentation-memcached/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-memcached/.npmignore
  plugins/node/opentelemetry-instrumentation-memcached/LICENSE
  plugins/node/opentelemetry-instrumentation-memcached/README.md
  plugins/node/opentelemetry-instrumentation-memcached/package.json
  plugins/node/opentelemetry-instrumentation-memcached/src/index.ts
  plugins/node/opentelemetry-instrumentation-memcached/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-memcached/src/types.ts
  plugins/node/opentelemetry-instrumentation-memcached/src/utils.ts
  plugins/node/opentelemetry-instrumentation-memcached/src/version.ts
  plugins/node/opentelemetry-instrumentation-memcached/test/index.test.ts
  plugins/node/opentelemetry-instrumentation-memcached/tsconfig.json
Labels: enhancement

#538 feat: add cassandra-driver instrumentation
  .github/workflows/unit-test.yml
  packages/opentelemetry-test-utils/testUtils.ts
  plugins/node/opentelemetry-instrumentation-cassandra/.eslintignore
  plugins/node/opentelemetry-instrumentation-cassandra/.eslintrc.js
  plugins/node/opentelemetry-instrumentation-cassandra/.npmignore
  plugins/node/opentelemetry-instrumentation-cassandra/LICENSE
  plugins/node/opentelemetry-instrumentation-cassandra/README.md
  plugins/node/opentelemetry-instrumentation-cassandra/package.json
  plugins/node/opentelemetry-instrumentation-cassandra/src/index.ts
  plugins/node/opentelemetry-instrumentation-cassandra/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-cassandra/src/types.ts
  plugins/node/opentelemetry-instrumentation-cassandra/src/version.ts
  plugins/node/opentelemetry-instrumentation-cassandra/test/cassandra-driver.test.ts
  plugins/node/opentelemetry-instrumentation-cassandra/tsconfig.json
Labels: enhancement
