Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2021-12, with the labels that each got.

#776 chore(ci): fix lint workflow
  .github/workflows/lint.yml
Labels: internal

#765 fix(user-interaction): handle null listener in addEventListener
  plugins/web/opentelemetry-instrumentation-user-interaction/src/instrumentation.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.nozone.test.ts
Labels: bug

#762 ci(husky): fix broken husky hooks
  .husky/commit-msg
  package.json
Labels: internal

#752 fix: early close of span with graphql execute
  plugins/node/opentelemetry-instrumentation-graphql/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-graphql/test/graphql.test.ts
Labels: bug

#764 fix(init-logger): init logger for react-load example
  examples/react-load/react/src/web-tracer.js
Labels: documentation

#779 feat: update host-metrics to api-metrics v0.27.0
  packages/opentelemetry-host-metrics/package.json
  packages/opentelemetry-host-metrics/src/BaseMetrics.ts
  packages/opentelemetry-host-metrics/src/metric.ts
  packages/opentelemetry-host-metrics/src/util.ts
  packages/opentelemetry-host-metrics/test/metric.test.ts
  packages/opentelemetry-host-metrics/test/util.test.ts
Labels: bug

#783 test: test multiple versions of `koa`
  plugins/node/opentelemetry-instrumentation-koa/.tav.yml
  plugins/node/opentelemetry-instrumentation-koa/package.json
Labels: internal

#653 feat(user-interaction): support for custom events and span enhancement
  plugins/web/opentelemetry-instrumentation-user-interaction/src/instrumentation.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/src/types.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/test/helper.test.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.nozone.test.ts
  plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.test.ts
Labels: enhancement

#792 test: test multiple versions of `bunyan`
  plugins/node/opentelemetry-instrumentation-bunyan/.tav.yml
  plugins/node/opentelemetry-instrumentation-bunyan/README.md
  plugins/node/opentelemetry-instrumentation-bunyan/package.json
Labels: internal

#777 chore: release main
  .release-please-manifest.json
  metapackages/auto-instrumentations-node/CHANGELOG.md
  metapackages/auto-instrumentations-node/package.json
  metapackages/auto-instrumentations-web/CHANGELOG.md
  metapackages/auto-instrumentations-web/package.json
  packages/opentelemetry-browser-extension-autoinjection/CHANGELOG.md
  packages/opentelemetry-browser-extension-autoinjection/package.json
  packages/opentelemetry-host-metrics/CHANGELOG.md
  packages/opentelemetry-host-metrics/package.json
  plugins/node/opentelemetry-instrumentation-graphql/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-graphql/package.json
  plugins/web/opentelemetry-instrumentation-user-interaction/CHANGELOG.md
  plugins/web/opentelemetry-instrumentation-user-interaction/package.json
Labels: autorelease: pending

#798 test(detector/gcp): ensure there is no loss of precision with large n…
  detectors/node/opentelemetry-resource-detector-gcp/test/detectors/GcpDetector.test.ts
Labels: internal

#778 feat(add-tav-action): add test-all-versions as github action
  .github/workflows/test-all-versions.yml
Labels: internal

#806 chore: update actions/checkout to v2
  .github/workflows/unit-test.yml
Labels: internal

#796 fix: NestJS Core Instrumentation: copy metadata to wrapped handler
  plugins/node/opentelemetry-instrumentation-nestjs-core/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-nestjs-core/test/index.test.ts
  plugins/node/opentelemetry-instrumentation-nestjs-core/test/setup.ts
Labels: bug

#800 fix(examples): fix React Load plugin example
  examples/react-load/react/README.md
  examples/react-load/react/docker/collector-config.yaml
  examples/react-load/react/docker/docker-compose.yaml
  examples/react-load/react/package.json
  examples/react-load/react/src/web-tracer.js
Labels: bug

#808 chore: release main
  .release-please-manifest.json
  plugins/node/opentelemetry-instrumentation-nestjs-core/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-nestjs-core/package.json
Labels: autorelease: pending
