Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2022-02, with the labels that each got.

#811 test(express-instrumentation): add test-all-versions
  plugins/node/opentelemetry-instrumentation-express/.tav.yml
  plugins/node/opentelemetry-instrumentation-express/package.json
Labels: internal

#851 chore: release main
  .release-please-manifest.json
  metapackages/auto-instrumentations-node/CHANGELOG.md
  metapackages/auto-instrumentations-node/package.json
  packages/opentelemetry-browser-extension-autoinjection/CHANGELOG.md
  packages/opentelemetry-browser-extension-autoinjection/package.json
  plugins/node/opentelemetry-instrumentation-aws-lambda/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-aws-lambda/package.json
  plugins/node/opentelemetry-instrumentation-express/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-express/package.json
  plugins/node/opentelemetry-instrumentation-generic-pool/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-generic-pool/package.json
  plugins/node/opentelemetry-instrumentation-graphql/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-graphql/package.json
  plugins/node/opentelemetry-instrumentation-nestjs-core/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-nestjs-core/package.json
  plugins/node/opentelemetry-instrumentation-restify/CHANGELOG.md
  plugins/node/opentelemetry-instrumentation-restify/package.json
Labels: autorelease: pending

#873 chore: add a few packages to release config
  release-please-config.json
Labels: internal

#869 feat(mongodb4): added mongodb4 instrumentation
  .github/workflows/unit-test.yml
  plugins/node/opentelemetry-instrumentation-mongodb/.tav.yml
  plugins/node/opentelemetry-instrumentation-mongodb/README.md
  plugins/node/opentelemetry-instrumentation-mongodb/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-mongodb/src/types.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb-v3.test.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb-v4.test.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/utils.ts
Labels: enhancement

#887 chore: add fastify to release manifest
  .release-please-manifest.json
Labels: internal

#891 fix: typo in fastify description
  plugins/node/opentelemetry-instrumentation-fastify/package.json
Labels: internal

#906 chore: remove deprecated dependency of codecov
  .github/workflows/unit-test.yml
  .nycrc
  detectors/node/opentelemetry-resource-detector-alibaba-cloud/package.json
  detectors/node/opentelemetry-resource-detector-aws/package.json
  detectors/node/opentelemetry-resource-detector-gcp/package.json
  detectors/node/opentelemetry-resource-detector-github/package.json
  metapackages/auto-instrumentations-node/package.json
  metapackages/auto-instrumentations-web/package.json
  package.json
  packages/opentelemetry-browser-extension-autoinjection/package.json
  packages/opentelemetry-host-metrics/package.json
  packages/opentelemetry-id-generator-aws-xray/package.json
  plugins/node/instrumentation-tedious/package.json
  plugins/node/opentelemetry-instrumentation-aws-lambda/package.json
  plugins/node/opentelemetry-instrumentation-aws-sdk/package.json
  plugins/node/opentelemetry-instrumentation-bunyan/package.json
  plugins/node/opentelemetry-instrumentation-cassandra/package.json
  plugins/node/opentelemetry-instrumentation-connect/package.json
  plugins/node/opentelemetry-instrumentation-dns/package.json
  plugins/node/opentelemetry-instrumentation-express/package.json
  plugins/node/opentelemetry-instrumentation-fastify/package.json
  plugins/node/opentelemetry-instrumentation-generic-pool/package.json
  plugins/node/opentelemetry-instrumentation-graphql/package.json
  plugins/node/opentelemetry-instrumentation-hapi/package.json
  plugins/node/opentelemetry-instrumentation-ioredis/package.json
  plugins/node/opentelemetry-instrumentation-knex/package.json
  plugins/node/opentelemetry-instrumentation-koa/package.json
  plugins/node/opentelemetry-instrumentation-memcached/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/package.json
  plugins/node/opentelemetry-instrumentation-mysql/package.json
  plugins/node/opentelemetry-instrumentation-mysql2/package.json
  plugins/node/opentelemetry-instrumentation-nestjs-core/package.json
  plugins/node/opentelemetry-instrumentation-net/package.json
  plugins/node/opentelemetry-instrumentation-pg/package.json
  plugins/node/opentelemetry-instrumentation-pino/package.json
  plugins/node/opentelemetry-instrumentation-redis/package.json
  plugins/node/opentelemetry-instrumentation-restify/package.json
  plugins/node/opentelemetry-instrumentation-router/package.json
  plugins/node/opentelemetry-instrumentation-winston/package.json
  plugins/web/opentelemetry-instrumentation-document-load/package.json
  plugins/web/opentelemetry-instrumentation-long-task/package.json
  plugins/web/opentelemetry-instrumentation-user-interaction/package.json
  plugins/web/opentelemetry-plugin-react-load/package.json
  propagators/opentelemetry-propagator-aws-xray/package.json
  propagators/opentelemetry-propagator-grpc-census-binary/package.json
  propagators/opentelemetry-propagator-ot-trace/package.json
Labels: internal

#863 feat(longtasks): allow callback to add span attributes on collection
  plugins/web/opentelemetry-instrumentation-long-task/README.md
  plugins/web/opentelemetry-instrumentation-long-task/src/instrumentation.ts
  plugins/web/opentelemetry-instrumentation-long-task/src/types.ts
  plugins/web/opentelemetry-instrumentation-long-task/test/longTask.test.ts
Labels: enhancement

#910 fix(documentation): mixed up winston readme for hook
  plugins/node/opentelemetry-instrumentation-winston/README.md
Labels: document

#903 fix(graphql): fix `graphql.operation.name` field
  plugins/node/opentelemetry-instrumentation-graphql/src/enums/AttributeNames.ts
  plugins/node/opentelemetry-instrumentation-graphql/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-graphql/test/graphql.test.ts
Labels: enhancement
