Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2022-01, with the labels that each got.

#821 ci: fix browser cache hashing issues
  .github/workflows/unit-test.yml
  package.json
  plugins/web/opentelemetry-instrumentation-long-task/package.json
Labels: internal

#731 updating web examples to latest
  examples/web/docker/collector-config.yaml
  examples/web/docker/docker-compose.yaml
  examples/web/examples/document-load/index.html
  examples/web/examples/document-load/index.js
  examples/web/examples/meta/index.js
  examples/web/examples/user-interaction/index.js
  examples/web/package.json
Labels: documentation

#809 test: NestsJS core instrumentation add test-all-versions
  plugins/node/opentelemetry-instrumentation-nestjs-core/.tav.yml
  plugins/node/opentelemetry-instrumentation-nestjs-core/package.json
Labels: tests

#603 Replace 55681 endpoint with 4318 endpoint for HTTP collector
  examples/connect/docker/docker-compose.yaml
  examples/fastify/docker/docker-compose.yaml
  examples/graphql/docker/docker-compose.yaml
  examples/web/docker/docker-compose.yaml
  packages/opentelemetry-browser-extension-autoinjection/src/types.ts
Labels: document

#463 feat(express): allow rewriting span names
  plugins/node/opentelemetry-instrumentation-express/README.md
  plugins/node/opentelemetry-instrumentation-express/package.json
  plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-express/src/types.ts
  plugins/node/opentelemetry-instrumentation-express/test/custom-config.test.ts
  plugins/node/opentelemetry-instrumentation-express/test/express.test.ts
  plugins/node/opentelemetry-instrumentation-express/test/hooks.test.ts
  plugins/node/opentelemetry-instrumentation-express/test/ignore-all.test.ts
  plugins/node/opentelemetry-instrumentation-express/test/utils.ts
Labels: enhancement

#850 fix(graphql): move graphql to dependencies
  plugins/node/opentelemetry-instrumentation-graphql/package.json
Labels: bug
