Repository open-telemetry/opentelemetry-js-contrib, pull requests merged in 2023-05, with the labels that each got.

#1432 fix(pg): Do not replace argument with plain object
  plugins/node/opentelemetry-instrumentation-pg/src/instrumentation.ts
Labels: pkg:instrumentation-pg

#1170 feat(mongodb): collect mongodb4 metrics
  plugins/node/opentelemetry-instrumentation-mongodb/examples/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/package.json
  plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts
  plugins/node/opentelemetry-instrumentation-mongodb/src/internal-types.ts
  plugins/node/opentelemetry-instrumentation-mongodb/src/types.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb-v3.test.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb-v4.metrics.test.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb-v4.test.ts
  plugins/node/opentelemetry-instrumentation-mongodb/test/utils.ts
Labels: pkg:instrumentation-mongodb

#1512 chore: mark plugin react load unmaintained
  plugins/web/opentelemetry-plugin-react-load/README.md
Labels: Component Ownership

#1516 chore: mark plugin connect unmaintained
  plugins/node/opentelemetry-instrumentation-connect/README.md
Labels: Component Ownership

#1515 chore: mark plugin dns unmaintained
  plugins/node/opentelemetry-instrumentation-dns/README.md
Labels: Component Ownership

#1514 chore: mark plugin hapi unmaintained
  plugins/node/opentelemetry-instrumentation-hapi/README.md
Labels: Component Ownership

#1513 chore: mark plugin koa unmaintained
  plugins/node/opentelemetry-instrumentation-koa/README.md
Labels: Component Ownership
